# This is a basic workflow to help you get started with Actions

name: Build pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - dev
      - feature/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: node setup
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
      - name: lint and format
        run: |
          npm install
          npm run format
          npm run lint
          
      - name: push format changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - applied format"
          git add --all
          git commit -m "Applied Format" || echo "No changes to commit"
          git push
