name: CI/CD feature

on:
  push:
    branches:
      - feature/*

  workflow_dispatch:

jobs:
  lint:
    uses: fraunhofer-iem/dodo-database-service/.github/workflows/lint.yml@main

  test:
    uses: fraunhofer-iem/dodo-database-service/.github/workflows/test.yml@main
  
  format:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: format
        run: |
          npm install
          npm run format

      - name: push format changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - applied format"
          git add --all
          git commit -m "Applied Format" || echo "No changes to commit"
          git push
