name: CI/CD feature

on:
  push:
    branches:
      - feature/*

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: node setup
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: lint and format
        run: |
          npm install
          npm run lint
  
  format:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: format
        run: |
          npm install
          npm run format

      - name: push format changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - applied format"
          git add --all
          git commit -m "Applied Format" || echo "No changes to commit"
          git push
