name: Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      prerelease:
        required: true
        type: boolean
     
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          prerelease: ${{ inputs.prerelease }}
          tag: ${{ inputs.tag }}
