name: test

on:
  workflow_call:
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: node setup
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: build and test
        run: |
          npm install
          npm run build
          npm test
